---
title: "checking exercise 1"
author: "Fangzhou Yang"
date: "10/05/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 11
**Functions: section 4.4.1, exercises 1**

```{r}
mergesort <- function (x) {
  # Check for a vector that doesn¡¯t need sorting
  len <-length(x)
  if (len < 2) result <- x
  else {
    #  sort x into result
    #  split x in half
    y <- x[1:(len / 2)]
    z <- x[(len/2+1):len]
    #  sort y and z
    y <- mergesort(y)
    z <- mergesort(z)
    #  merge y and z into a sorted result
    result <- c()
    #  while (some are left in both piles)
    while (min(length(y), length(z)) > 0) {
    #  put the largest first element on the end
    #  remove it from y or z
      if (y[1] > z[1]) {
        result <- c(result, y[1])
        y <- y[-1]
      } else {
        result <- c(result, z[1])
        z <- z[-1]
      }
    }
    #  put the leftovers onto the end of result
    if (length(y) > 0)
    result <- c(result, y)
    else
    result <- c(result, z)
  }
  return(result)
}
```
