---
title: "For loops exerise 3"
author: "Fangzhou Yang"
date: "10/03/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 2
**For loops: section 4.1.1, exercises 3**

(a).answer=15
```{r}
answer <- 0
for (j in 1:5) answer <- answer + j
answer
```

(b).answer={1,2,3,4,5}
```{r}
answer <- NULL
for (j in 1:5) answer <- c(answer, j)
answer
```

(c).answer={0,1,2,3,4,5}
```{r}
answer <- 0
for (j in 1:5) answer <- c(answer, j)
answer
```

(d).answer=120
```{r}
answer <- 1
for (j in 1:5) answer <- answer * j
answer
```

(e).answer={3,21,23,6,11,14,5,4,28,10,8,25,20,17,26,27}
```{r}
answer <- 3
for (j in 1:15) answer <- c(answer, (7 * answer[j]) %% 31)
answer
```

So if we rewrite the code by use j from 1 to 30(or larger), we can find that the sequence is repeated every 16 elements. So from the 17th element of the sequence, it repeats {3,21,23,5,11,15,12,22,30,24,13,29,17,26,27} again.
```{r}
answer <- 3
for (j in 1:30) answer <- c(answer, (7 * answer[j]) %% 31)
answer
```
